% EX1 : Example 1 from paper:
%       L.G. Van Willigenburg, W.L. De Koning, 2013,
%       "Temporal and one-step stabilisability and detectability of
%        discrete time linear systems",
%       IET Control Theory & Applications, 7, 1, 151-159
%       Download this paper from:
%       http://gvw007.yolasite.com/resources/TempOneIET2013.pdf

%% Compute continuous-time optimal control
p=0; tlsbang; tu =[]; ts=0.2; % ts=0.1
for t=0:ts:4; tu=[tu; t signsc(prod(t-tsw),ub(2),ub(1))]; end
%save tlssol ts tsw f x0 tu tf tt xt;% Results saved in file tlssol.mat

%% Compute the digital optimal control using opconstr1
% Initialize the solution with the continuous-time optimal control
% clear; load tlssol;
t=[0:ts:tf]'; tu=pwaver(tu,t);
% Settings for opconstr
fopt(1)=1; fopt(2)=1e-2; fopt(3)=1e-2; fopt(4)=1e-2;
% Digital optimal control computation
[tu,tx,tla,tt,xt,yt,J]=opconstr1('tlsdop','','dop1',fopt,1,tu,x0);
hf=figure(1); print(hf,'Fig1.emf','-dmeta'); % Save figure

%% Compute equivalent discrete-time LQG problem data
clear; lqgcomp('tlsdyn','tlsout','tlsphi','tlslqgc','dop1','montcar',3);
load edorp; % Load equivalent discrete-time LQG problem data generated by lqgcomp

%% Temporal stabilizability and detectability analysis
js=2; ks=js; tolWM=1e-6; epsrw=1e-6; %tolWM=1e-9; epsrw=1e-9;
[npt,nst,ptt,stt,NW,NM,rW,rM,nAD,hfs]=tmpstdt(lqgarr,js,ks,tolWM,epsrw,epsrw);

%% Display and export results
print(hfs(1),'Fig2.emf','-dmeta'); % Save figure
print(hfs(2),'Fig3.emf','-dmeta'); % Save figure
% Display table
disp('     i rank(W) rank(M) nAD'); disp([[0:length(nAD)-1]' rW rM nAD]);
% Write to excel to export to word
table1=[[0:length(nAD)-1]' rW rM nAD]; xlswrite('table1.xls',table1);