% EX2 : Example 2 from paper:
%       L.G. Van Willigenburg, W.L. De Koning, 2013,
%       "Temporal and one-step stabilisability and detectability of
%        discrete time linear systems",
%       IET Control Theory & Applications, 7, 1, 151-159
%       Download this paper from:
%       http://gvw007.yolasite.com/resources/TempOneIET2013.pdf

%% Digital optimal control computation
fopt(1)=1; fopt(2)=1e-2; fopt(3)=1e-2; fopt(4)=1e-2;
[tu,tx,tla,tt,xt,yt,J]=opconstr1('tlsdop1','','dop2',fopt,1);
hf=figure(1); plot(tx(:,1),tx(:,2:end-1)*diag([1e-4 1e-2 1e-1])); hold on;
stair(tu(:,1),tu(:,2:end)); hold off; 
xlabel('time'); ylabel('Control & States'); title('Optimal state & digital control');
print(hf,'Fig4.emf','-dmeta'); % Save figure

%% Compute equivalent discrete-time LQG problem data
clear; lqgcomp('tlsdyn1','tlsout1','tlsphi1','tlslqgc','dop2','montcar',3);
load edorp; % Load equivalent discrete-time LQG problem data generated by lqgcomp
js=3; ks=js; tolWM=1e-6; epsrw=1e-6;

%% Temporal stabilizability and detectability analysis
[npt,nst,ptt,stt,NW,NM,rW,rM,nAD,hfs]=tmpstdt(lqgarr,js,ks,tolWM,epsrw,epsrw);

%% Display and export results
print(hfs(1),'Fig5.emf','-dmeta');
nsd=(nst(1:end-1)-nst(2:end))./nst(2:end);
hf=figure; plot(NW(1:end-1),nsd,'o');
strpl='Relative one-step stabilizability measure (||S_{i}^{\epsilon}||-||S_{i+1}^{\epsilon}||)/||S_{i+1}^{\epsilon}||';
title(strpl); xlabel('Discrete-time'); ylabel(strpl)
print(hf,'Fig6.emf','-dmeta');
% Display table
disp('     i rank(W) rank(M) nAD'); disp([[0:length(nAD)-1]' rW rM nAD]);
% Write to excel to export to word
table1=[[0:length(nAD)-1]' rW rM nAD]; xlswrite('table2.xls',table1);